// Loader
window.addEventListener('load', () => {
  const loader = document.getElementById('loader');
  setTimeout(() => loader.classList.add('hide'), 400);
});

// Year
document.getElementById('year').textContent = new Date().getFullYear();

// Sticky nav state
const nav = document.getElementById('nav');
const backToTop = document.getElementById('backToTop');
window.addEventListener('scroll', () => {
  const scrolled = window.scrollY > 40;
  nav.classList.toggle('scrolled', scrolled);
  backToTop.classList.toggle('show', window.scrollY > 600);
}, { passive: true });

// Mobile nav toggle
const navToggle = document.getElementById('navToggle');
const navLinks = document.getElementById('navLinks');
navToggle.addEventListener('click', () => {
  navToggle.classList.toggle('open');
  navLinks.classList.toggle('open');
});
navLinks.querySelectorAll('a').forEach(link => {
  link.addEventListener('click', () => {
    navToggle.classList.remove('open');
    navLinks.classList.remove('open');
  });
});

// Scroll reveal
const revealEls = document.querySelectorAll('.reveal');
const revealObserver = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('in');
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.15, rootMargin: '0px 0px -60px 0px' });
revealEls.forEach((el, i) => {
  el.style.transitionDelay = `${Math.min(i % 4, 3) * 0.08}s`;
  revealObserver.observe(el);
});

// Cursor glow (desktop only)
const cursorGlow = document.getElementById('cursorGlow');
if (matchMedia('(hover: hover)').matches) {
  window.addEventListener('mousemove', (e) => {
    cursorGlow.style.left = e.clientX + 'px';
    cursorGlow.style.top = e.clientY + 'px';
  });
}

// ---------------------------------------------------------------------------
// Listing demo — DEVELOPMENT FIXTURES ONLY.
// This page has no access to the real GarnettWork Teaser/Truth backend, so
// results below are hand-written illustrative fixtures, not live decisions.
// Never present this output as a real GarnettWork Truth result.
// ---------------------------------------------------------------------------
const FIXTURES = {
  ps5Disc: {
    intent: 'BUY',
    identity: 'PlayStation 5 — Disc Edition (825GB, original)',
    verdict: 'PASS',
    reason: 'Canonical identity confirmed and the asking price sits inside the verified fair range with room to spare.',
    askingPrice: '$260',
    landedPrice: '$260 (local pickup, no shipping)',
    comparableCount: '41 verified comparables',
    fairRange: '$255 – $295',
    maxSafeBuy: '$280',
    risks: ['None flagged'],
    unknowns: ['Controller/cable completeness not stated by seller'],
    receiptStatus: 'Fixture receipt — evidence trail not generated by a live service',
  },
  switchOled: {
    intent: 'BUY',
    identity: 'Nintendo Switch OLED — Standard (64GB)',
    verdict: 'PASS',
    reason: 'Canonical identity confirmed and comparable depth supports this as a fair-to-good price.',
    askingPrice: '$185',
    landedPrice: '$196 (incl. estimated shipping)',
    comparableCount: '33 verified comparables',
    fairRange: '$180 – $210',
    maxSafeBuy: '$205',
    risks: ['Battery health not disclosed'],
    unknowns: ['Dock and Joy-Con grips included or separate'],
    receiptStatus: 'Fixture receipt — evidence trail not generated by a live service',
  },
  ps5SlimRefuse: {
    intent: 'BUY',
    identity: 'PlayStation 5 Slim — Disc Edition (1TB)',
    verdict: 'REFUSE',
    reason: "Comparable market depth for this SKU is currently insufficient. GarnettWork refuses rather than guess at a fair price.",
    askingPrice: '$310',
    landedPrice: 'Not calculated — REFUSE',
    comparableCount: 'Insufficient verified comparables',
    fairRange: 'Unavailable',
    maxSafeBuy: 'Not supported yet',
    risks: ['Unknown — insufficient evidence to assess'],
    unknowns: ['Comparable sale depth for this specific SKU', 'Regional price variance'],
    receiptStatus: 'Fixture receipt — evidence trail not generated by a live service',
  },
  genericRefuse: {
    intent: 'BUY',
    identity: 'Unrecognized or unsupported product',
    verdict: 'REFUSE',
    reason: 'This product is outside GarnettWork’s currently proven Truth support. The Factory may be collecting evidence for it, but collection is not the same as proven support.',
    askingPrice: '—',
    landedPrice: '—',
    comparableCount: 'Not evaluated',
    fairRange: 'Unavailable',
    maxSafeBuy: 'Not supported yet',
    risks: ['Unknown — no Truth support for this product yet'],
    unknowns: ['Identity', 'Market evidence', 'Fair price range'],
    receiptStatus: 'Fixture receipt — evidence trail not generated by a live service',
  },
};

function matchFixture(text) {
  const t = text.toLowerCase();
  const mentionsSwitch = t.includes('switch');
  const mentionsOled = t.includes('oled');
  const mentionsPs5 = t.includes('ps5') || t.includes('playstation 5') || t.includes('playstation5');
  const mentionsSlimOr1tb = t.includes('slim') || t.includes('1tb') || t.includes('1 tb');

  if (mentionsSwitch && mentionsOled) return FIXTURES.switchOled;
  if (mentionsPs5 && mentionsSlimOr1tb) return FIXTURES.ps5SlimRefuse;
  if (mentionsPs5) return FIXTURES.ps5Disc;
  return FIXTURES.genericRefuse;
}

function verdictClass(verdict) {
  if (verdict === 'PASS') return '';
  if (verdict === 'FAIL') return 'truth-fail';
  return 'truth-badge-refuse';
}

function renderResult(fixture) {
  const wrap = document.getElementById('demoResultWrap');
  const badgeClass = verdictClass(fixture.verdict);
  wrap.innerHTML = `
    <div class="fixture-banner">
      &#9888; DEVELOPMENT FIXTURE — illustrative only, not a live GarnettWork Truth result.
    </div>
    <div class="result-card">
      <div class="result-head">
        <h3>${fixture.identity}</h3>
        <span class="truth-badge ${badgeClass}">${fixture.verdict}</span>
      </div>
      <p class="result-reason">${fixture.reason}</p>
      <div class="result-fields">
        <div class="result-field"><span>Asking Price</span><p>${fixture.askingPrice}</p></div>
        <div class="result-field"><span>Shipping / Landed Price</span><p>${fixture.landedPrice}</p></div>
        <div class="result-field"><span>Verified Comparables</span><p>${fixture.comparableCount}</p></div>
        <div class="result-field"><span>Verified Fair Range</span><p>${fixture.fairRange}</p></div>
        <div class="result-field"><span>Max Safe Buy</span><p>${fixture.maxSafeBuy}</p></div>
        <div class="result-field"><span>Evidence / Receipt</span><p>${fixture.receiptStatus}</p></div>
      </div>
      <div class="result-lists">
        <div class="result-list">
          <h4>Known Risks</h4>
          <ul>${fixture.risks.map(r => `<li>${r}</li>`).join('')}</ul>
        </div>
        <div class="result-list">
          <h4>Unknowns</h4>
          <ul>${fixture.unknowns.map(u => `<li>${u}</li>`).join('')}</ul>
        </div>
      </div>
    </div>
  `;
}

const listingForm = document.getElementById('listingForm');
listingForm.addEventListener('submit', (e) => {
  e.preventDefault();
  const value = document.getElementById('listingInput').value.trim();
  if (!value) return;
  const fixture = matchFixture(value);
  renderResult(fixture);
  document.getElementById('demo').scrollIntoView({ behavior: 'smooth', block: 'start' });
});

// Contact form (static demo submission)
const form = document.getElementById('contactForm');
const formNote = document.getElementById('formNote');
form.addEventListener('submit', (e) => {
  e.preventDefault();
  const btn = form.querySelector('button[type="submit"] span');
  const originalText = btn.textContent;
  btn.textContent = 'Sending...';
  setTimeout(() => {
    btn.textContent = originalText;
    formNote.textContent = "Thanks — we'll be in touch within one business day.";
    form.reset();
  }, 900);
});
